termux-setup-storage
apt-get install update
apt-get install upgrade
apt-get install curl
apt-get install wget
apt-get install git
apt-get install bash
apt-get install python
apt-get install python2
apt-get install python3
apt-get install pip
apt-get install pip2
apt-get install ruby
apt-get install perl
apt-get install php
apt-get install gem
apt-get install php-cli
apt-get install cowsay
apt-get install figlet
apt-get install lolcat
apt-get install toilet
apt-get install nodejs
apt-get install npm
apt-get install nano
apt-get install nmap
apt-get install vim
apt-get install micro
apt-get install tmux
